Repository wecode-bootcamp-korea/22-2nd-GREAM-frontend, pull requests merged in 2021-07, with the labels that each got.

#1 [22기 박정훈] Add: 3차 초기세팅 완료
  src/components/Card/Card.jsx
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.jsx
  src/index.js
  src/pages/Detail/Detail.jsx
  src/pages/Login/Login.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/Shop/Shop.jsx
  src/pages/SignUp/SignUp.jsx
Labels: Status: 리뷰 요청

#4 [22기 오지수] Modify: setFlex 위치 수정
  src/index.js
  src/styles/theme.js
Labels: Status: Accepted

#5 [22기 오지수] fontawesome npm install
  package-lock.json
  package.json
  src/pages/Detail/Detail.jsx
Labels: Status: Accepted

#6 [22기 오지수] Modify: theme Mixin 수정
  src/styles/theme.js
Labels: Status: Accepted

#8 [22기 오지수] Add: Common Button Style 추가
  src/styles/theme.js
Labels: Status: 리뷰 요청

#9 [22기 오지수] fontawesome 라이브러리 삭제 & fontawesome, font 관련 코드 수정
  package-lock.json
  package.json
  public/index.html
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#12 [22기 오지수] Footer layout 스타일 코드 작성 완료
  src/components/Footer/Footer.jsx
Labels: Status: Accepted

#11 [22기 오지수] 상세페이지 전반적인 레이아웃 & 스타일 & 기능 부여
  public/favicon.ico
  src/images/sample.png
  src/pages/Detail/Detail.jsx
  src/pages/Detail/SectionLeft/Carousel/Carousel.jsx
  src/pages/Detail/SectionLeft/SectionLeft.jsx
  src/pages/Detail/SectionRight/Confirmation/Confirmation.jsx
  src/pages/Detail/SectionRight/History/History.jsx
  src/pages/Detail/SectionRight/InfoHeader/ButtonGroup/Button/Button.jsx
  src/pages/Detail/SectionRight/InfoHeader/ButtonGroup/ButtonGroup.jsx
  src/pages/Detail/SectionRight/InfoHeader/InfoHeader.jsx
  src/pages/Detail/SectionRight/Modal/Modal.jsx
  src/pages/Detail/SectionRight/Modal/ModalTableGroup/ModalTableGroup.jsx
  src/pages/Detail/SectionRight/More/More.jsx
  src/pages/Detail/SectionRight/PaintInfo/PaintInfo.jsx
  src/pages/Detail/SectionRight/SectionRight.jsx
  src/pages/Detail/SectionRight/TableComponent/TableComponent.jsx
  src/pages/Detail/SectionRight/Title/Title.jsx
  src/pages/Detail/SectionRight/TransactionGraph/TransactionGraph.jsx
  src/styles/theme.js
Labels: Status: Review 진행중

#14 [22기 이경민] SignUp 리뷰반영 완료
  .eslintrc
  src/pages/SignUp/SignUp.jsx
Labels: Status: 리뷰 요청

#13 [22기 박정훈] shop 페이지 전반적인 레이아웃 & 스타일 & 기능 부여 / 리뷰 반영 완료
  package-lock.json
  package.json
  public/data/ShopCard.json
  public/data/best.json
  public/data/filter.json
  public/index.html
  src/Routes.js
  src/config.js
  src/pages/Shop/Category/Category.jsx
  src/pages/Shop/ProductList/Card/Card.jsx
  src/pages/Shop/ProductList/ProductList.jsx
  src/pages/Shop/ProductList/Sort/SortList.jsx
  src/pages/Shop/Shop.jsx
  src/pages/Shop/ShopHeader/ShopHeader.jsx
  src/pages/Shop/SideFilterList/DropDownFilter/DropDownFilter.jsx
  src/pages/Shop/SideFilterList/SideFilterBox/SideFilterBox.jsx
  src/pages/Shop/SideFilterList/SideFilterList.jsx
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#17 [22기 오지수] 동적 라우팅 코드 수정, Carousel 기능 추가, footer 코드 수정
  src/Routes.js
  src/components/Footer/Footer.jsx
  src/config.js
  src/pages/Detail/Detail.jsx
  src/pages/Detail/SectionLeft/Carousel/Carousel.jsx
  src/pages/Detail/SectionLeft/SectionLeft.jsx
  src/pages/Detail/SectionRight/SectionRight.jsx
  src/pages/Shop/ProductList/Card/Card.jsx
  src/pages/Shop/ProductList/ProductList.jsx
Labels: Status: 리뷰 요청

#18 [22기 오지수] Graph 구현 완료
  src/components/Nav/Nav.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/SectionLeft/SectionLeft.jsx
  src/pages/Detail/SectionRight/History/History.jsx
  src/pages/Detail/SectionRight/SectionRight.jsx
  src/pages/Detail/SectionRight/TransactionGraph/Graph/Graph.jsx
  src/pages/Detail/SectionRight/TransactionGraph/TransactionGraph.jsx
Labels: Status: Accepted

#23 [22기 오지수] 데이터 통신, Detail Margin 조정
  src/config.js
  src/pages/Detail/Detail.jsx
  src/pages/Detail/SectionLeft/Carousel/Carousel.jsx
  src/pages/Detail/SectionLeft/SectionLeft.jsx
  src/pages/Detail/SectionRight/History/History.jsx
  src/pages/Detail/SectionRight/InfoHeader/ButtonGroup/Button/Button.jsx
  src/pages/Detail/SectionRight/InfoHeader/ButtonGroup/ButtonGroup.jsx
  src/pages/Detail/SectionRight/InfoHeader/InfoHeader.jsx
  src/pages/Detail/SectionRight/Modal/Modal.jsx
  src/pages/Detail/SectionRight/Modal/ModalTableGroup/ModalTableGroup.jsx
  src/pages/Detail/SectionRight/PaintInfo/PaintInfo.jsx
  src/pages/Detail/SectionRight/SectionRight.jsx
  src/pages/Detail/SectionRight/TransactionGraph/Graph/Graph.jsx
  src/pages/Detail/SectionRight/TransactionGraph/TransactionGraph.jsx
Labels: Status: 리뷰 요청

#24 [22기 오지수] chart.js 라이브러리 package.json에 추가
  package-lock.json
  package.json
  src/pages/Detail/SectionLeft/SectionLeft.jsx
Labels: Status: 리뷰 요청

#19 [22기 박정훈] shop페이지 side 필터링 🚨
  src/config.js
  src/pages/Shop/ProductList/Card/Card.jsx
  src/pages/Shop/ProductList/ProductList.jsx
  src/pages/Shop/Shop.jsx
  src/pages/Shop/SideFilterList/DropDownFilter/DropDownFilter.jsx
  src/pages/Shop/SideFilterList/SideFilterBox/SideFilterBox.jsx
  src/pages/Shop/SideFilterList/SideFilterList.jsx
  src/pages/SignUp/SignUp.jsx
Labels: Status: 리뷰 요청

#25 [22기 오지수] modal 수정, Carousel 위치 조정
  src/components/Nav/Nav.jsx
  src/pages/Detail/SectionLeft/SectionLeft.jsx
  src/pages/Detail/SectionRight/Modal/Modal.jsx
  src/pages/Detail/SectionRight/More/More.jsx
Labels: Status: 리뷰 요청

#16 [22기 이경민] (Bid 구매)currentBuyingPrice,currentSellingPrice 의 값에 따른 화면 변화 구현
  src/Routes.js
  src/pages/Bid/Bid.jsx
  src/pages/BidPerchase/BidDeadlineComponent.jsx
  src/pages/BidPerchase/BidPerchase.jsx
  src/pages/BidPerchase/SuggestPricePerchaseComponent.jsx
  src/pages/BidSale/BidSale.jsx
Labels: Status: Conflict 해결 요청, Status: 수정 요청

#22 [22기 이경민] 전화번호 인풋 우측 증감 화살표 삭제
  src/pages/SignUp/SignUp.jsx
Labels: Status: Conflict 해결 요청

#26 [22기 오지수] Nav 로고 클릭했을 때 전체 데이터가 보여지도록 수정
  src/Routes.js
  src/components/Nav/Nav.jsx
  src/components/ScrollToTop/ScrollToTop.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/SectionRight/History/History.jsx
  src/pages/Detail/SectionRight/Modal/ModalTableGroup/ModalTableGroup.jsx
  src/pages/Detail/SectionRight/PaintInfo/PaintInfo.jsx
  src/pages/Detail/SectionRight/SectionRight.jsx
  src/pages/Detail/SectionRight/TransactionGraph/Graph/Graph.jsx
Labels: Status: 리뷰 요청

#28 [22기 오지수] 구매/판매 버튼 로직 이상 발견하여 수정
  src/pages/Detail/SectionRight/InfoHeader/ButtonGroup/Button/Button.jsx
  src/pages/Detail/SectionRight/InfoHeader/ButtonGroup/ButtonGroup.jsx
Labels: Status: 리뷰 요청

#29 [22기 오지수] 메뉴바 로그인으로 가는 onClick 이벤트 추가
  src/components/Nav/Nav.jsx
Labels: Status: 리뷰 요청

#30 [22기 박정훈] 필터 및 페이지네이션 완료
  package-lock.json
  public/data/pageNation.json
  src/components/ScrollToTop/ScrollToTop.jsx
  src/config.js
  src/pages/Shop/Category/Category.jsx
  src/pages/Shop/ProductList/ProductList.jsx
  src/pages/Shop/ProductList/Sort/SortList.jsx
  src/pages/Shop/Shop.jsx
  src/pages/Shop/SideFilterList/DropDownFilter/DropDownFilter.jsx
  src/pages/Shop/SideFilterList/SideFilterBox/SideFilterBox.jsx
  src/pages/Shop/SideFilterList/SideFilterList.jsx
Labels: Status: 리뷰 요청

#34 [22기 오지수]Modify: color.join('/')
  src/pages/Detail/SectionRight/PaintInfo/PaintInfo.jsx
Labels: Status: 리뷰 요청

#33 [22기 박정훈] 샵페이지 버튼 디자인 수정
  src/pages/Shop/ProductList/ProductList.jsx
Labels: Status: 리뷰 요청

#36 [22기 오지수] sortDate 함수 추가, modal props 추가
  src/config.js
  src/pages/Detail/SectionRight/Modal/Modal.jsx
  src/pages/Detail/SectionRight/Modal/ModalTableGroup/ModalTableGroup.jsx
  src/pages/Detail/SectionRight/SectionRight.jsx
  src/pages/Detail/SectionRight/TransactionGraph/TransactionGraph.jsx
Labels: Status: 리뷰 요청

#37 [22기 이경민] 최종 머지 요청
  src/components/Nav/Nav.jsx
  src/config.js
  src/pages/BidPerchase/BidPerchase.jsx
  src/pages/BidPerchase/ImmediatePerchaseComponent.jsx
  src/pages/BidPerchase/SuggestPricePerchaseComponent.jsx
  src/pages/BidSale/BidDeadlineComponent.jsx
  src/pages/BidSale/BidSale.jsx
  src/pages/BidSale/ImmediateSaleComponent.jsx
  src/pages/BidSale/SuggestPriceSaleComponent.jsx
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
Labels: Status: 도움 요청
